name: 'dbt_stocks'
version: '1.0.0'
config-version: 2

profile: 'dbt_stocks'

# Paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  dbt_stocks:
    bronze:
      +materialized: view

    silver:
      +materialized: view

    gold:
      +materialized: table
